//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- common_types.go ---

func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PortConfig) DeepCopyInto(out *PortConfig) {
	*out = *in
	if in.Additional != nil {
		in, out := &in.Additional, &out.Additional
		*out = make([]NamedPort, len(*in))
		copy(*out, *in)
	}
}

func (in *PortConfig) DeepCopy() *PortConfig {
	if in == nil {
		return nil
	}
	out := new(PortConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedPort) DeepCopyInto(out *NamedPort) {
	*out = *in
}

func (in *NamedPort) DeepCopy() *NamedPort {
	if in == nil {
		return nil
	}
	out := new(NamedPort)
	in.DeepCopyInto(out)
	return out
}

func (in *ConsensusConfig) DeepCopyInto(out *ConsensusConfig) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

func (in *ConsensusConfig) DeepCopy() *ConsensusConfig {
	if in == nil {
		return nil
	}
	out := new(ConsensusConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *P2PConfig) DeepCopyInto(out *P2PConfig) {
	*out = *in
	if in.BootstrapNodes != nil {
		in, out := &in.BootstrapNodes, &out.BootstrapNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *P2PConfig) DeepCopy() *P2PConfig {
	if in == nil {
		return nil
	}
	out := new(P2PConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *APIConfig) DeepCopyInto(out *APIConfig) {
	*out = *in
	if in.MetricsEnabled != nil {
		in, out := &in.MetricsEnabled, &out.MetricsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowedHosts != nil {
		in, out := &in.AllowedHosts, &out.AllowedHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *APIConfig) DeepCopy() *APIConfig {
	if in == nil {
		return nil
	}
	out := new(APIConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *KeyManagementSpec) DeepCopyInto(out *KeyManagementSpec) {
	*out = *in
	if in.KMS != nil {
		in, out := &in.KMS, &out.KMS
		*out = new(KMSKeyConfig)
		**out = **in
	}
}

func (in *KeyManagementSpec) DeepCopy() *KeyManagementSpec {
	if in == nil {
		return nil
	}
	out := new(KeyManagementSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KMSKeyConfig) DeepCopyInto(out *KMSKeyConfig) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
}

func (in *KMSKeyConfig) DeepCopy() *KMSKeyConfig {
	if in == nil {
		return nil
	}
	out := new(KMSKeyConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *KMSSecretRef) DeepCopyInto(out *KMSSecretRef) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
}

func (in *KMSSecretRef) DeepCopy() *KMSSecretRef {
	if in == nil {
		return nil
	}
	out := new(KMSSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *SeedRestoreSpec) DeepCopyInto(out *SeedRestoreSpec) {
	*out = *in
}

func (in *SeedRestoreSpec) DeepCopy() *SeedRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(SeedRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SnapshotScheduleSpec) DeepCopyInto(out *SnapshotScheduleSpec) {
	*out = *in
}

func (in *SnapshotScheduleSpec) DeepCopy() *SnapshotScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *UpgradeStrategySpec) DeepCopyInto(out *UpgradeStrategySpec) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheckBetweenRestarts != nil {
		in, out := &in.HealthCheckBetweenRestarts, &out.HealthCheckBetweenRestarts
		*out = new(bool)
		**out = **in
	}
}

func (in *UpgradeStrategySpec) DeepCopy() *UpgradeStrategySpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeStrategySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HealthPolicySpec) DeepCopyInto(out *HealthPolicySpec) {
	*out = *in
	if in.RequireInboundPeers != nil {
		in, out := &in.RequireInboundPeers, &out.RequireInboundPeers
		*out = new(bool)
		**out = **in
	}
}

func (in *HealthPolicySpec) DeepCopy() *HealthPolicySpec {
	if in == nil {
		return nil
	}
	out := new(HealthPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StartupGateSpec) DeepCopyInto(out *StartupGateSpec) {
	*out = *in
}

func (in *StartupGateSpec) DeepCopy() *StartupGateSpec {
	if in == nil {
		return nil
	}
	out := new(StartupGateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ChainRef) DeepCopyInto(out *ChainRef) {
	*out = *in
}

func (in *ChainRef) DeepCopy() *ChainRef {
	if in == nil {
		return nil
	}
	out := new(ChainRef)
	in.DeepCopyInto(out)
	return out
}

func (in *PluginSpec) DeepCopyInto(out *PluginSpec) {
	*out = *in
}

func (in *PluginSpec) DeepCopy() *PluginSpec {
	if in == nil {
		return nil
	}
	out := new(PluginSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *InitSpec) DeepCopyInto(out *InitSpec) {
	*out = *in
	out.Image = in.Image
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PluginSpec, len(*in))
		copy(*out, *in)
	}
}

func (in *InitSpec) DeepCopy() *InitSpec {
	if in == nil {
		return nil
	}
	out := new(InitSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
	if in.RunAsGroup != nil {
		in, out := &in.RunAsGroup, &out.RunAsGroup
		*out = new(int64)
		**out = **in
	}
	if in.FSGroup != nil {
		in, out := &in.FSGroup, &out.FSGroup
		*out = new(int64)
		**out = **in
	}
}

func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *S3SnapshotSpec) DeepCopyInto(out *S3SnapshotSpec) {
	*out = *in
}

func (in *S3SnapshotSpec) DeepCopy() *S3SnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(S3SnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CloudSpec) DeepCopyInto(out *CloudSpec) {
	*out = *in
	if in.APIImage != nil {
		in, out := &in.APIImage, &out.APIImage
		*out = new(ImageSpec)
		**out = **in
	}
	if in.WebImage != nil {
		in, out := &in.WebImage, &out.WebImage
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *CloudSpec) DeepCopy() *CloudSpec {
	if in == nil {
		return nil
	}
	out := new(CloudSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayRoute) DeepCopyInto(out *GatewayRoute) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitConfig)
		**out = **in
	}
}

func (in *GatewayRoute) DeepCopy() *GatewayRoute {
	if in == nil {
		return nil
	}
	out := new(GatewayRoute)
	in.DeepCopyInto(out)
	return out
}

func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
}

func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// --- nodecluster_types.go ---

func (in *NodeCluster) DeepCopyInto(out *NodeCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *NodeCluster) DeepCopy() *NodeCluster {
	if in == nil {
		return nil
	}
	out := new(NodeCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NodeClusterList) DeepCopyInto(out *NodeClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NodeClusterList) DeepCopy() *NodeClusterList {
	if in == nil {
		return nil
	}
	out := new(NodeClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NodeClusterSpec) DeepCopyInto(out *NodeClusterSpec) {
	*out = *in
	out.Image = in.Image
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Ports.DeepCopyInto(&out.Ports)
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Consensus != nil {
		in, out := &in.Consensus, &out.Consensus
		*out = new(ConsensusConfig)
		(*in).DeepCopyInto(*out)
	}
	in.P2P.DeepCopyInto(&out.P2P)
	in.API.DeepCopyInto(&out.API)
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = new(KeyManagementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SeedRestore != nil {
		in, out := &in.SeedRestore, &out.SeedRestore
		*out = new(SeedRestoreSpec)
		**out = **in
	}
	if in.SnapshotSchedule != nil {
		in, out := &in.SnapshotSchedule, &out.SnapshotSchedule
		*out = new(SnapshotScheduleSpec)
		**out = **in
	}
	in.UpgradeStrategy.DeepCopyInto(&out.UpgradeStrategy)
	in.HealthPolicy.DeepCopyInto(&out.HealthPolicy)
	if in.StartupGate != nil {
		in, out := &in.StartupGate, &out.StartupGate
		*out = new(StartupGateSpec)
		**out = **in
	}
	if in.Chains != nil {
		in, out := &in.Chains, &out.Chains
		*out = make([]ChainRef, len(*in))
		copy(*out, *in)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(InitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolConfig != nil {
		in, out := &in.ProtocolConfig, &out.ProtocolConfig
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	in.Security.DeepCopyInto(&out.Security)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KMSSecrets != nil {
		in, out := &in.KMSSecrets, &out.KMSSecrets
		*out = make([]KMSSecretRef, len(*in))
		copy(*out, *in)
	}
}

func (in *NodeClusterSpec) DeepCopy() *NodeClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NodeClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NodeClusterStatus) DeepCopyInto(out *NodeClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NodeClusterStatus) DeepCopy() *NodeClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NodeClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// --- chain_types.go ---

func (in *Chain) DeepCopyInto(out *Chain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Chain) DeepCopy() *Chain {
	if in == nil {
		return nil
	}
	out := new(Chain)
	in.DeepCopyInto(out)
	return out
}

func (in *Chain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChainList) DeepCopyInto(out *ChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Chain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChainList) DeepCopy() *ChainList {
	if in == nil {
		return nil
	}
	out := new(ChainList)
	in.DeepCopyInto(out)
	return out
}

func (in *ChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ChainSpec) DeepCopyInto(out *ChainSpec) {
	*out = *in
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EVMConfig != nil {
		in, out := &in.EVMConfig, &out.EVMConfig
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ProtocolConfig != nil {
		in, out := &in.ProtocolConfig, &out.ProtocolConfig
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ChainSpec) DeepCopy() *ChainSpec {
	if in == nil {
		return nil
	}
	out := new(ChainSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ChainStatus) DeepCopyInto(out *ChainStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ChainStatus) DeepCopy() *ChainStatus {
	if in == nil {
		return nil
	}
	out := new(ChainStatus)
	in.DeepCopyInto(out)
	return out
}

// --- indexer_types.go ---

func (in *Indexer) DeepCopyInto(out *Indexer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Indexer) DeepCopy() *Indexer {
	if in == nil {
		return nil
	}
	out := new(Indexer)
	in.DeepCopyInto(out)
	return out
}

func (in *Indexer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *IndexerList) DeepCopyInto(out *IndexerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Indexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *IndexerList) DeepCopy() *IndexerList {
	if in == nil {
		return nil
	}
	out := new(IndexerList)
	in.DeepCopyInto(out)
	return out
}

func (in *IndexerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *IndexerSpec) DeepCopyInto(out *IndexerSpec) {
	*out = *in
	out.Image = in.Image
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(S3SnapshotSpec)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *IndexerSpec) DeepCopy() *IndexerSpec {
	if in == nil {
		return nil
	}
	out := new(IndexerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *IndexerStatus) DeepCopyInto(out *IndexerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *IndexerStatus) DeepCopy() *IndexerStatus {
	if in == nil {
		return nil
	}
	out := new(IndexerStatus)
	in.DeepCopyInto(out)
	return out
}

// --- explorer_types.go ---

func (in *Explorer) DeepCopyInto(out *Explorer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Explorer) DeepCopy() *Explorer {
	if in == nil {
		return nil
	}
	out := new(Explorer)
	in.DeepCopyInto(out)
	return out
}

func (in *Explorer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ExplorerList) DeepCopyInto(out *ExplorerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Explorer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ExplorerList) DeepCopy() *ExplorerList {
	if in == nil {
		return nil
	}
	out := new(ExplorerList)
	in.DeepCopyInto(out)
	return out
}

func (in *ExplorerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ExplorerSpec) DeepCopyInto(out *ExplorerSpec) {
	*out = *in
	out.BackendImage = in.BackendImage
	if in.FrontendImage != nil {
		in, out := &in.FrontendImage, &out.FrontendImage
		*out = new(ImageSpec)
		**out = **in
	}
	in.Database.DeepCopyInto(&out.Database)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ExplorerSpec) DeepCopy() *ExplorerSpec {
	if in == nil {
		return nil
	}
	out := new(ExplorerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ExplorerStatus) DeepCopyInto(out *ExplorerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ExplorerStatus) DeepCopy() *ExplorerStatus {
	if in == nil {
		return nil
	}
	out := new(ExplorerStatus)
	in.DeepCopyInto(out)
	return out
}

// --- bridge_types.go ---

func (in *Bridge) DeepCopyInto(out *Bridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Bridge) DeepCopy() *Bridge {
	if in == nil {
		return nil
	}
	out := new(Bridge)
	in.DeepCopyInto(out)
	return out
}

func (in *Bridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BridgeList) DeepCopyInto(out *BridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BridgeList) DeepCopy() *BridgeList {
	if in == nil {
		return nil
	}
	out := new(BridgeList)
	in.DeepCopyInto(out)
	return out
}

func (in *BridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BridgeSpec) DeepCopyInto(out *BridgeSpec) {
	*out = *in
	out.ServerImage = in.ServerImage
	if in.UIImage != nil {
		in, out := &in.UIImage, &out.UIImage
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *BridgeSpec) DeepCopy() *BridgeSpec {
	if in == nil {
		return nil
	}
	out := new(BridgeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BridgeStatus) DeepCopyInto(out *BridgeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BridgeStatus) DeepCopy() *BridgeStatus {
	if in == nil {
		return nil
	}
	out := new(BridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// --- gateway_types.go ---

func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

func (in *Gateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewayList) DeepCopyInto(out *GatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Gateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GatewayList) DeepCopy() *GatewayList {
	if in == nil {
		return nil
	}
	out := new(GatewayList)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]GatewayRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(RateLimitConfig)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// --- network_types.go ---

func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

func (in *Network) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NetworkList) DeepCopyInto(out *NetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Network, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NetworkList) DeepCopy() *NetworkList {
	if in == nil {
		return nil
	}
	out := new(NetworkList)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]NamedNodeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Chains != nil {
		in, out := &in.Chains, &out.Chains
		*out = make([]NamedChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]NamedIndexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Explorers != nil {
		in, out := &in.Explorers, &out.Explorers
		*out = make([]NamedExplorer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bridges != nil {
		in, out := &in.Bridges, &out.Bridges
		*out = make([]NamedBridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]NamedGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(CloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// --- Named* wrappers ---

func (in *NamedNodeCluster) DeepCopyInto(out *NamedNodeCluster) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *NamedNodeCluster) DeepCopy() *NamedNodeCluster {
	if in == nil {
		return nil
	}
	out := new(NamedNodeCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedChain) DeepCopyInto(out *NamedChain) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *NamedChain) DeepCopy() *NamedChain {
	if in == nil {
		return nil
	}
	out := new(NamedChain)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedIndexer) DeepCopyInto(out *NamedIndexer) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *NamedIndexer) DeepCopy() *NamedIndexer {
	if in == nil {
		return nil
	}
	out := new(NamedIndexer)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedExplorer) DeepCopyInto(out *NamedExplorer) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *NamedExplorer) DeepCopy() *NamedExplorer {
	if in == nil {
		return nil
	}
	out := new(NamedExplorer)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedBridge) DeepCopyInto(out *NamedBridge) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *NamedBridge) DeepCopy() *NamedBridge {
	if in == nil {
		return nil
	}
	out := new(NamedBridge)
	in.DeepCopyInto(out)
	return out
}

func (in *NamedGateway) DeepCopyInto(out *NamedGateway) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *NamedGateway) DeepCopy() *NamedGateway {
	if in == nil {
		return nil
	}
	out := new(NamedGateway)
	in.DeepCopyInto(out)
	return out
}
